### ISSUE TITLE
build_dataset文件找不到

### ISSUE THREAD

**Issue by linkang-els** [boheumd/ASM-Loc#3]
大佬您好，感谢您的分享！我最近在阅读您的论文并尝试复现它。环境：python3.7，Ubuntu16.04，requirements.txt里的环境也安装好了。data和datase的文件我是从[ACM-Net](https://github.com/ispc-lab/ACM-Net)里下载。
在执行python main_THUMOS.py --batch_size 16时输出：
Traceback (most recent call last):
  File "/home/lk/lk/ASM-Loc-main/main_THUMOS.py", line 10, in <module>
    from dataset import build_dataset, my_collate_fn
ImportError: cannot import name 'build_dataset' from 'dataset' (/home/lk/lk/ASM-Loc-main/dataset/__init__.py)

请问我该如何解决上述问题？期待得到您的解答

**Comment by boheumd** [comment]
你好，我看了一下我这边的dataset.py文件里面的确有build_dataset这个function 
https://github.com/boheumd/ASM-Loc/blob/main/dataset.py#L274
你应该不需要下载ACM-Net的dataset文件夹等code，只需要从ACM-Net里下载里面提供的extracted features就行。

**Comment by linkang-els** [comment]
> 你好，我看了一下我这边的dataset.py文件里面的确有build_dataset这个function https://github.com/boheumd/ASM-Loc/blob/main/dataset.py#L274 你应该不需要下载ACM-Net的dataset文件夹等code，只需要从ACM-Net里下载里面提供的extracted feature

问题解决啦，谢谢您！
