### ISSUE TITLE
I don't understand the parameter t_factor in the code

### ISSUE THREAD

**Issue by freeman-1995** [boheumd/ASM-Loc#7]
(args.segment_frames_num * vid_len) / (args.frames_per_sec * args.test_upgrade_scale * input_feature.shape[1])
Numerator is the total frame numbers of the video
denominator I cannot understand

**Comment by boheumd** [comment]
Hi, (args.segment_frames_num * vid_len) / args.frames_per_sec is the video duration. input_feature.shape[1] is the temporal length of the feature (=T). When we do testing, we will upsample the output score by args.test_upgrade_scale, as we have shown in https://github.com/boheumd/ASM-Loc/blob/018d396a2044a61cb1b117459cc5d2db2877b965/main_THUMOS.py#L318.
